title: 显然，同理，略......
author: Keming
email: kemingy94@gmail.com
description: El Psy Congroo

# socail links
github_username: kemingy
twitter_username: urcyanide
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# google analytics
google_analytics: UA-116310410-1

excerpts:
  enable: true
  length: 300

# remote_theme: kemingy/jekyll-theme-ink

permalink: /blog/:title

favicon:
  enable: true
  name: favicon.ico

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

markdown: kramdown
kramdown:
  input: GFM

mathjax:
  enable: true
  cdn: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-MML-AM_CHTML

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!-- more -->

jekyll-archives:
  enabled: [categories, year, month, tags]
  layouts:
    category: 'category'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/tag/:name/'
    category: '/category/:name/'

